# basic config file for NGRC.py
# this file is used for code development

# time parameters 
dt: 0.0025
startTime: 0.0
warmupTime: 2.0
trainTime: 10.0
testTime: 10.0
errorTime: 1.0

# data generation parameters
system: 'Lorenz_63'
numerical_integrator: 'rk4'

# feature vector parameters
k: 2
s: 1
p: 2

# regression parameters
regression_method: 'ridge'
lambda1: 1.5e-6
lambda2: 1.5e-6
tolerance: 1.0e-7
maxIterations: 200000000

# plot parameters
plotPath: 'results/plot.png'

