# basic config file for NGRC.py
# this file is used for code development

# time parameters 
dt: 0.0025
startTime: 0.0
warmupTime: 2.0075
trainTime: 1.01
testTime: 2.01
plotTime: 0.01
errorTime: 1.01



# data generation parameters
system: 'Lorenz_63'
numerical_integrator: 'rk4'


# feature vector parameters
k: 2
s: 1
p: 2


# regression parameters
regression_method: 'ridge'
lambda1: 1.5e-6
lambda2: 1.5e-6
tolerance: 1.0e-6
maxIterations: 100000000

